### ISSUE TITLE
Looking for VR Input Emulator... ERROR

### ISSUE THREAD

**Issue by Luvvydev** [naelstrof/VRPlayspaceMover#7]
Looking for SteamVR...Success!
Looking for VR Input Emulator...

Never finds Emulator, it's installed correctly and even shows up as a menu option within VR

**Comment by JordieVRChat** [comment]
Found and ran: Boost6005BugFixApplier.exe

It still inputs "Looking for VR Input Emulator..." without working.

**Comment by naelstrof** [comment]
Oof. Then I'm unsure. Sorry. It uses boost interprocess comminations to communicate if that helps

**Comment by JordieVRChat** [comment]
okaee, thanks for your fast replies and help regardless <3

**Comment by zoth138** [comment]
I am currently having this issue and have tried the fix. Any workarounds? i'd even reinstall windows to test

**Comment by naelstrof** [comment]
You probably should not reinstall windows, part of of the bug is that your Windows error log is empty. Reinstalling Windows would probably clear your error log (causing the bug).

If you ran the bug fix applier from here https://drive.google.com/open?id=1Gn3IOm6GbkINplbEenu0zTr3DkB1E8Hc, and it still doesn't work, then I don't know what to do. Sorry!

**Comment by naelstrof** [comment]
Oh you should also try this fix: https://github.com/sharkyh20/OpenVR-InputEmulator/releases/tag/SteamVR-Fix

**Comment by zoth138** [comment]
finding a workaround atm as the fixes didnt fix.  After following a reddit post, playspace mover no longer immediately  says it can't find input emulator, but instead just keeps searching. I'm hoping to find a complete fix soon, I will try to keep updating with progress
https://www.reddit.com/r/Vive/comments/a12pim/safe_mode_a_living_hell/ease8jk/

**Comment by Olavmeister** [comment]
I also have this problem. Is here anyone that knows how to fix this? I've contacted many people and they have no idea what the problem is, Neither do I.

**Comment by zoth138** [comment]
No fix yet. I'm still working on it after classes and work.

**Comment by eilerj2** [comment]
I was running into input emulator issues until I used this driver fix. Not sure if it will help.

https://github.com/sharkyh20/OpenVR-InputEmulator/releases/tag/SteamVR-Fix

**Comment by zoth138** [comment]
currently testing and think i found a huge issue people may be doing. Are people still using this version of advanced settings? :
https://github.com/naelstrof/VRPlayspaceMover/releases

**Comment by zoth138** [comment]
I fixed my playspace mover by:
using this version of advanced settings https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/releases
Updating SteamVR out of beta and to version 1.2.7
repeatedly crashing my computer (idk why)
Losing access to camera (idk why)
and using the most recent release of VRPlaysspaceMover found on this github's release pages.
NOTHING was run as admin and I did NOT have to set the file to read only.

**Comment by Olavmeister** [comment]
Just letting you know that It's still not working for me. Steam VR is not in safe mode either, I've also downloaded the patch and other ''fixes'' but my placespacemover.exe is still stuck on ''Looking For VR Input Emulator.'' I really hope someone could help me.I haven't been able to use playspacemover since Steam VR got that update....

**Comment by King-Gilgamess** [comment]
https://www.youtube.com/watch?v=20oCnsgM9fI Step by step guide. I did not make this video but this worked for me and the maker made it with the idea of of going through the process semi pain free. Only difference i noticed in my files was that under the  drivers i only had the .exe file not the text document. the file with both is in the description of the video. Hope this helps resolve the issues with not being able to launch playspace mover.

**Comment by SergeantDeppen** [comment]
I know this is an old post but I have noticed that if steam VR ever crashes it blocks some apps and it did that with open VR for me! I went into my steamVR settings and had to go to start up and shut down than click choose start up overlay apps and select advanced settings and VR input emulator.

**Comment by AllyAran** [comment]
I had this issue and dug around trying to find a fix and found this post. Here's what my issue was.
Fix:
Launch SteamVR>Click 3 dash menu>settings> Advanced settings "Show"> Startup / Shutdown > "Manage Add-Ons"> 00vrinputemulator "On"

When I did this, I restarted SteamVR and launched it by running playspace mover again
Hope this helps!
